version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: echo_api_server
    ports:
      - "8080:8080"
    # Mounts the local directory so your app detects future code/env changes faster
    volumes:
      - ./.env:/.env
    # Instructs Docker Compose to parse and pass your env variables
    env_file:
      - .env
    environment:
      - NODE_ENV=development